default: &DEFAULT
  gpu_available: true
  working_dir: .
  parameters_file: hparams.yaml
  parameters_choice: pretrained # enumerated in parameters file
  loss_plots_dir: ./plots

local: 
  <<: *DEFAULT
  gpu_available: false